### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by alibazlamit**
@ericknauer Could you please review the readme.md and possible merge this branch to master.
Thanks.

### CODE REVIEW

**Comment by alibazlamit** [comment]
@ericknauer a friendly reminder could you take a look at the readme.me so we can merge this PR into master.
Thanks.

**Comment by ericknauer** [comment]
Hi Ali,

Yes, I've been working on it but haven't checked any changes back in yet.
There are a significant number of changes that need to be made, so it is
taking a while. :-)

I'll see about wrapping it up in the next day or two.

I have some concerns about the in-line documentation / descriptions that
are in 'clients.py'.

Take lines 62 to 74 for example:

---
 def delete_datacenter(self, datacenter_id):
        """
        Removes the server from your Datacenter.

        :param      datacenter_id: The unique ID of the Datacenter.
        :type       datacenter_id: ``str``

        """
        response = self._perform_request(
            url='/datacenters/%s' % (datacenter_id),
            type='DELETE')

        return response
---

I'm not sure why that says "Removes the server..." when it is actually
going to remove the entire data center.

I'm also not sure why "Datacenter" is capitalized, and not two words. There
are similar inconsistencies elsewhere in the code.

I don't know if fixing up items like that should happen before this release
is published, or if it is something we would need to postpone till later,
assuming the info in README.md and the supplied examples are correct.

Eric

**Comment by alibazlamit** [comment]
@ericknauer Thanks for the update, just let me know once you are done so i can update those changes.

**Comment by edevenport** [comment]
We should update the in-code documentation too so that is is accurate and consistent. It appears some of that might have been copied/paste when the SDK was originally created.

@alibazlamit Can you look to update the in-code documentation and @ericknauer can focus on the README. I would like to get the Python SDK wrapped up by end of week.

**Comment by ericknauer** [comment]
Ali - I'm finished up with the README.md now, so this should be ready to merge.

**Comment by alibazlamit** [comment]
Thanks @ericknauer i am sorry there were a lot of things to fix.
@edevenport lets merge this.

**Pull request merged**
